### ISSUE TITLE
Unable to connect to AP R2500 V2.0

### ISSUE THREAD

**Issue by Massu4** [jinglemansweep/hacs-allpowers#7]
Unfortunately I'm unable to connect to AP R2500 V2.0. 
Bluetooth address has been found, but failed to connect message appears.

**Comment by merewords** [comment]
The exact same problem with an AP R600 V2.0,

HA discovers the device
![image](https://github.com/user-attachments/assets/f52cbf36-7889-41f8-a09b-2be4f4c88b3d)
But when we try and connect
![image](https://github.com/user-attachments/assets/513a3b34-b64b-413e-930f-9c9c52c562ab)
it thinks about it for a while
![image](https://github.com/user-attachments/assets/df5b3425-3b05-499e-b04d-31e23b863500)
And the fails
![image](https://github.com/user-attachments/assets/3a5511c4-ff3e-4ab9-92be-41c405fabd3f)

**Comment by merewords** [comment]
Here is the error log:

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/allpowers_ble/allpowers.py:232
integration: allpowers_ble (documentation)
First occurred: 07:02:44 (7 occurrences)
Last logged: 08:56:46

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 310, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 254, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/allpowers_ble/allpowers.py", line 248, in _reconnect
    await self._ensure_connected()
  File "/config/custom_components/allpowers_ble/allpowers.py", line 232, in _ensure_connected
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 472, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 339, in _raise_if_needed
    raise BleakConnectionError(msg) from exc
bleak_retry_connector.BleakConnectionError: AP R600 V2.0 - 2A:02:01:39:8A:63: Failed to connect after 6 attempt(s): [org.bluez.Error.Failed] Operation already in progress`

**Comment by DNASystem** [comment]
Hi I configured an esp32 bluetooth proxy I added r2500 it does not update the data after a while it goes into lock I try to turn on and off the various sockets I get this error:
Unable to perform action: switch/turn_on Characteristic 0000FFF2-0000-1000-8000-00805F9B34FB was not found!
could you help me how to solve thanks

**Comment by euroman2007** [comment]
i have the same problem here with my AP-R600 V2.0
is there any solution ?

**Comment by KW1963** [comment]
I have still the Same Problem with my AP-R600 V2.0… discovered with Mac-Adresse, but no Connection.

**Comment by asiersan** [comment]
Same problem with an AP R600 V2.0 here.
